# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c54d4f1f90ad0a8014ed52dff6054f9befa830a61de1fdaf24c7c3b0a59fcd396771c8dee04318254c89012648628082525e1b7bbc2e1ace8545ccac94efd1

test:
  secret_key_base: 795c05b3ea6ce45ebe7e295db7a027c32b0408e368a79cde2e0d95114f7534565582b057dd65d75da5548ace8b0474efd5bfdc16af3e326a5feb634a6fac9f83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
